language: python
python:
  - "3.6"
cache: pip
before_install:
  - openssl aes-256-cbc -K $encrypted_fcc88e7d9f85_key -iv $encrypted_fcc88e7d9f85_iv
    -in environment.yml.enc -out environment.yml -d
install:
  - pip install -r requirements.txt
script:
  - pylint --output-format=parseable core
  - behave --no-capture --tags @smoke,@acceptance --tags ~@wip --summary --no-capture
notifications:
  email: true